SISkripsi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('base.urls', namespace='base')),
    url(r'^admin/', admin.site.urls),
    url(r'^proposal/', include('proposal.urls', namespace='proposal')),
    url(r'^skripsi/', include('skripsi.urls', namespace='skripsi')),
    url(r'^yudisium/', include('yudisium.urls', namespace='yudisium')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from django.conf.urls import url
from base.views import *
from django.contrib.auth.decorators import login_required


app_name = 'base'


urlpatterns = [
    url(r'^$', Index.as_view(), name='index'),
    url(r'^home/$', login_required(Home.as_view()), name='home'),
    url(r'^logout/$', logout_view, name='logout'),
]

proposal/urls.py
# coding=utf-8


"""
xcfhjk
"""


from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from proposal.views import *

app_name = 'proposal'

urlpatterns = [
    url(r'^$', login_required(Index.as_view()), name='index'),
    url(r'^edit/(?P<pk>[0-9]+)/$', Edit.as_view(), name='edit'),
    url(r'^bimbingan/$', login_required(Bimbingan.as_view()), name='bimbingan'),
    url(r'^seminar', login_required(Seminar.as_view()), name='seminar'),
    ]

skripsi/urls.py
from django.conf.urls import include, url
from skripsi.views import *

app_name = 'skripsi'

urlpatterns = [
    url(r'^$', dexskripsi, name='dexskripsi'),
    url(r'^bimbingan/', ListBimbingan.as_view(), name='bimbingan'),
    url(r'^sidang', sidang, name='sidang')
]

yudisium/urls.py
from django.conf.urls import include, url
from yudisium.views import *

app_name = 'yudisium'

urlpatterns = [
    url(r'^$', revisi, name='revisi'),
    url(r'^jurnal/$', jurnal, name='jurnal'),
    url(r'^sidang/$', sidang, name='sidang'),
    url(r'^wisuda/$', wisuda, name='wisuda'),

]

base/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Mahasiswa(models.Model):
    akunMhs = models.OneToOneField(User,
                                   on_delete=models.CASCADE,
                                   related_name='akunMhs')
    npm = models.CharField(max_length=14, unique=True)
    posisi = models.CharField(max_length=1, default='A')

    def __str__(self):
        return self.akunMhs.username


class Dosen(models.Model):
    akunDsn = models.OneToOneField(User,
                                   on_delete=models.CASCADE,
                                   related_name="akunDsn")
    nidn = models.CharField(max_length=10, unique=True)
    gelar = models.CharField(max_length=25,
                             default="M. Kom"
                             )

    def __str__(self):
        return self.akunDsn.first_name + " " + self.akunDsn.last_name

base/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.Form):
    username = forms.CharField(max_length=15)
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

base/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from base.forms import UserForm


class Index(View):
    form_class = UserForm
    template_name = 'indexform.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # untuk login
    def post(self, request):
        form = self.form_class(request.POST)
        username = form.data.get('username')
        password = form.data.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('base:home')

        return render(request, self.template_name,{'form': form})



class Home(View):
    template_name = 'home.html'
    context = {}

    def get(self, request):
        return render(request, self.template_name, self.context)


def logout_view(request):
    logout(request)
    return redirect("base:index")

base/templates/base.html
{% load staticfiles%}
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'mui/css/mui.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'mui/side/style.css' %}" rel="stylesheet" type="text/css" />
    <link rel="shortcut icon" type="image/png" href="{% static 'image/favicon.png' %}"/>
    <script src="{% static 'mui/js/mui.min.js' %}"></script>
    <script src="{% static 'mui/side/jquery-2.1.4.min.js' %}"></script>
    <script src="{% static 'mui/side/script.js' %}"></script>
    <title>{% block title %} SISkripsi {% endblock %}</title>

  </head>
  <body>
    <div id="sidedrawer" class="mui--no-user-select">
      <div id="sidedrawer-brand" class="mui--appbar-line-height">
        <span class="mui--text-title">SISkripsi</span>
      </div>
      <div class="mui-divider">
      </div>
      <ul>
        <li>
           <strong>Beranda</strong>
           <ul>
             <li><a href="{% url 'base:home' %}">Me </a> </li>
             <li><a href="{% url 'base:logout' %}">Logout </a> </li>
           </ul>
        </li>
        <li>
          <strong>Proposal</strong>
          <ul>
            <li><a href="{% url 'proposal:index'%}">Identitas Proposal</a></li>
            <li><a href="{% url 'proposal:bimbingan'%}">Bimbingan Proposal</a></li>
            <li><a href="{% url 'proposal:seminar'%}">Seminar Proposal</a></li>
          </ul>
        </li>
        <li>
          <strong>Skripsi</strong>
          <ul>
            <li><a href="{% url 'skripsi:dexskripsi' %}">Identitas Skripsi</a></li>
            <li><a href="{% url 'skripsi:bimbingan' %}">Bimbingan Skripsi</a></li>
            <li><a href="{% url 'skripsi:sidang' %}">Sidang</a></li>
          </ul>
        </li>
        <li>
          <strong>Yudisium</strong>
          <ul>
            <li><a href="{% url 'yudisium:sidang' %}">Sidang</a></li>
            <li><a href="{% url 'yudisium:revisi' %}">Revisi</a></li>
            <li><a href="{% url 'yudisium:jurnal' %}">Jurnal</a></li>
            <li><a href="{% url 'yudisium:wisuda' %}">Wisuda</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <header id="header">
      <div class="mui-appbar mui--appbar-line-height">
        <div class="mui-container-fluid">
          <a class="sidedrawer-toggle mui--visible-xs-inline-block mui--visible-sm-inline-block js-show-sidedrawer">☰</a>
          <a class="sidedrawer-toggle mui--hidden-xs mui--hidden-sm js-hide-sidedrawer">☰ <span style="text-align: center; font-size: 32;">{% block judul %}  etaaa  {% endblock %}</span> </a>
          <span class="mui--text-title mui--visible-xs-inline-block mui--visible-sm-inline-block">SISkripsi</span>
        </div>
      </div>
    </header>
    <div id="content-wrapper" style=" padding-top: 30px ">
      <div class="mui--appbar-height"></div>
      <div class="mui-container-fluid">
        {% block content %}
        Etaah
        {% endblock %}

      </div>
    </div>
    <!--<footer id="footer">-->
      <!--<div class="mui-container-fluid">-->

      <!--</div>-->
    <!--</footer>-->
  </body>
</html>

base/templates/dex.html
{% load staticfiles%}
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sistem Informasi Skripsi</title>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="//cdn.muicss.com/mui-0.9.30/extra/mui-colors.min.css">
    <script src="//cdn.muicss.com/mui-0.9.30/extra/mui-combined.min.js"></script>
    <style>
     /**
     * Body CSS
     */
    html,
    body {
      height: 100%;
    }

    html,
    body,
    input,
    textarea,
    buttons {
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      text-shadow: 1px 1px 1px rgba(0, 0, 0, 0.004);
    }


    /**
     * Header CSS
     */
    header {
      position: fixed;
      top: 0;
      right: 0;
      left: 0;
      z-index: 2;
    }

    header ul.mui-list--inline {
      margin-bottom: 0;
    }

    header a {
      color: #fff;
    }

    header table {
      width: 100%;
    }


    /**
     * Content CSS
     */
    #content-wrapper {
      min-height: 100%;

      /* sticky footer */
      box-sizing: border-box;
      margin-bottom: -100px;
      padding-bottom: 100px;
    }


    /**
     * Footer CSS
     */
    footer {
      box-sizing: border-box;
      height: 100px;
      background-color: #eee;
      border-top: 1px solid #e0e0e0;
      padding-top: 35px;
    }

    </style>
  </head>
  <body>
    <header class="mui-appbar mui--z1">
      <!-- Appbar HTML goes here -->
      <div class="mui-container">
  <table>
    <tr class="mui--appbar-height">
      <td class="mui--text-title">SISkripsi</td>
      <td class="mui--text-right">
        <ul class="mui-list--inline mui--text-body2">
          <li><a href="#">About</a></li>
        </ul>
      </td>
    </tr>
  </table>
</div>

    </header>
    <div id="content-wrapper" class="mui--text-center">
      <!-- Content HTML goes here -->
      <div class="mui--appbar-height">
        
      </div>
      <br>
      <br>
      <div class="mui--text-display2 row wow fadeInDownBig">Sistem Informasi Skripsi</div>
      <br>
      <br>
      <i class="fa fa-university fa-5x mui--text-display3 mui--color-grey row wow zoomIn" aria-hidden="true"></i>

      <br>
      <br>
      <div class="mui-row">
        <div class="mui-col-xs-4 mui-col-xs-offset-4 row" style="border: 2px black solid">
          <form class="mui-form" action="{% url 'base:login' %}" method="post">
            {% csrf_token %}
            <legend>Login untuk melanjutkan</legend>
            <div class="mui-textfield mui-textfield--float-label row wow fadeInRightBig">
              <input type="email" id="email" name="email">
              <label>Surel</label>
            </div>
            <div class="mui-textfield mui-textfield--float-label row wow fadeInLeftBig">
              <input type="password" id="pw" name="pw">
              <label>Kata Sandi</label>
            </div>
            
            <button type="submit" class="mui-btn mui-btn--primary"> Login </button>

          </form>
        </div>
      </div>
    </div>
    <footer>
      <div class="mui-container mui--text-center">
       
      </div>
    </footer>
    <script src="//cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>
    <script>
      new WOW().init();
    </script>

  </body>
</html>

base/templates/form.html
<div>
    <form class="mui-form" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="mui-textfield">
                <label> {{ field.tag }} </label>
                {{ field }}
            </div>
        {% endfor %}
    </form>
</div>

base/templates/home.html
{%extends "base.html" %}
{%block title%} SISkripsi {%endblock%}

{% load staticfiles %}

{% block judul %}
{{home}}
{% endblock %}

{%block content%}
<div style="text-align: center;">
	<div class="mui-col-md-4">
		<div class="mui-panel">
			<h2> Proposal </h2>
			<input type="checkbox"> Dosen Pembimbing
		</div>

	</div>

	<div class="mui-col-md-4">
		<div class="mui-panel">
			<h2> Skripsi </h2>

		</div>

	</div>

	<div class="mui-col-md-4">
		<div class="mui-panel">
			<h2> Yudisium </h2>
		</div>

	</div>
</div>

{%endblock%}

base/templates/indexform.html
{% load staticfiles%}
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Sistem Informasi Skripsi</title>
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="//cdn.muicss.com/mui-0.9.30/extra/mui-colors.min.css">
    <script src="//cdn.muicss.com/mui-0.9.30/extra/mui-combined.min.js"></script>
    <style>
     /**
     * Body CSS
     */
    html,
    body {
      height: 100%;
    }

    html,
    body,
    input,
    textarea,
    buttons {
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      text-shadow: 1px 1px 1px rgba(0, 0, 0, 0.004);
    }


    /**
     * Header CSS
     */
    header {
      position: fixed;
      top: 0;
      right: 0;
      left: 0;
      z-index: 2;
    }

    header ul.mui-list--inline {
      margin-bottom: 0;
    }

    header a {
      color: #fff;
    }

    header table {
      width: 100%;
    }


    /**
     * Content CSS
     */
    #content-wrapper {
      min-height: 100%;

      /* sticky footer */
      box-sizing: border-box;
      margin-bottom: -100px;
      padding-bottom: 100px;
    }


    /**
     * Footer CSS
     */
    footer {
      box-sizing: border-box;
      height: 100px;
      background-color: #eee;
      border-top: 1px solid #e0e0e0;
      padding-top: 35px;
    }

    </style>
  </head>
  <body>
    <header class="mui-appbar mui--z1">
      <!-- Appbar HTML goes here -->
      <div class="mui-container">
  <table>
    <tr class="mui--appbar-height">
      <td class="mui--text-title">SISkripsi</td>
      <td class="mui--text-right">
        <ul class="mui-list--inline mui--text-body2">
          <li><a href="#">About</a></li>
        </ul>
      </td>
    </tr>
  </table>
</div>

    </header>
    <div id="content-wrapper" class="mui--text-center">
      <!-- Content HTML goes here -->
      <div class="mui--appbar-height">
        
      </div>
      <br>
      <br>
      <div class="mui--text-display2 row wow fadeInDownBig">Sistem Informasi Skripsi</div>
      <br>
      <br>
      <i class="fa fa-university fa-5x mui--text-display3 mui--color-grey row wow zoomIn" aria-hidden="true"></i>

      <br>
      <br>
      <div class="mui-row">
        <div class="mui-col-xs-4 mui-col-xs-offset-4 row" style="border: 2px black solid">
          <form class="mui-form" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <legend>Login untuk melanjutkan</legend>
            <h2> {{form.errors}}</h2>
            <div class="mui-textfield mui-textfield--float-label row wow fadeInRightBig">
              {{form.username}}
              <label>Surel</label>
            </div>
            <div class="mui-textfield mui-textfield--float-label row wow fadeInLeftBig">
              {{form.password}}
              <label>Kata Sandi</label>
            </div>

            <button type="submit" class="mui-btn mui-btn--primary"> Login </button>

          </form>
        </div>
      </div>
    </div>
    <footer>
      <div class="mui-container mui--text-center">
       
      </div>
    </footer>
    <script src="//cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>
    <script>
      new WOW().init();
    </script>

  </body>
</html>