SISkripsi/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('base.urls', namespace='base')),
    url(r'^admin/', admin.site.urls),
    url(r'^proposal/', include('proposal.urls', namespace='proposal')),
    url(r'^skripsi/', include('skripsi.urls', namespace='skripsi')),
    url(r'^yudisium/', include('yudisium.urls', namespace='yudisium')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/urls.py
from django.conf.urls import url
from base.views import *
from django.contrib.auth.decorators import login_required


app_name = 'base'


urlpatterns = [
    url(r'^$', Index.as_view(), name='index'),
    url(r'^home/$', login_required(Home.as_view()), name='home'),
    url(r'^logout/$', logout_view, name='logout'),
]

proposal/urls.py
# coding=utf-8


"""
xcfhjk
"""


from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from proposal.views import *

app_name = 'proposal'

urlpatterns = [
    url(r'^$', login_required(Index.as_view()), name='index'),
    url(r'^edit/(?P<pk>[0-9]+)/$', Edit.as_view(), name='edit'),
    url(r'^bimbingan/$', login_required(Bimbingan.as_view()), name='bimbingan'),
    url(r'^seminar', login_required(Seminar.as_view()), name='seminar'),
    ]

proposal/models.py
from django.utils import timezone

from django.db import models as md

from base.models import *


# Create your models here.


class Proposal(md.Model):
    """
        Ini adalah model untuk identitas proposal
    """
    akun = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                related_name="mhsAkun", blank=True)
    judul = models.TextField(max_length=500, unique=True)
    katakunci = models.TextField(max_length=500)
    ringkasan = models.TextField(max_length=1000)
    dospem = models.ForeignKey(Dosen, on_delete=models.DO_NOTHING, blank=True)
    lolos = models.BooleanField(default=False)

    def __str__(self):
        return "Proposal untuk " + self.akun.username


class BimbinganProposal(md.Model):
    """
        Ini untuk mencatat hasil bimbingan
    """
    proposal = models.ForeignKey(Proposal,
                                 on_delete=models.CASCADE,
                                 related_name="propID", blank=True)
    tanggal = md.DateField(default=timezone.now)
    hasil = md.TextField(max_length=500)

    def __str__(self):
        return "Bimbingan untuk " + self.proposal.judul


class SeminarProposal(md.Model):
    # diisi oleh mahasiswa
    fileProposal = models.FileField()

    # diisi oleh sistem
    proposal = models.OneToOneField(Proposal,
                                    on_delete=models.CASCADE,
                                    related_name="propSid",
                                    unique=True, blank=True)
    masabimbingan = models.BooleanField(default=True)

    # disi oleh admin
    tanggal = models.DateField(default=timezone.now, blank=True,null=True)
    tempat = models.CharField(max_length=30, blank=True, null=True)

    # diisi oleh dosen pembimbing
    dospemsetuju = models.BooleanField(default=False, blank=True)

    # diisi oleh kaprodi
    penguji1 = models.ForeignKey(Dosen,
                                 on_delete=models.CASCADE,
                                 related_name="penguji1",
                                 blank=True, null=True)
    penguji2 = models.ForeignKey(Dosen,
                                 on_delete=models.CASCADE,
                                 related_name="penguji2",
                                 blank=True, null=True)

    def __str__(self):
        return "Sidang untuk " + self.proposal.judul

proposal/forms.py
# coding=utf-8

from proposal.models import BimbinganProposal, SeminarProposal, Proposal
from base.models import Dosen
from django import forms


class Tanggal(forms.widgets.DateInput):
	input_type = 'date'


class Texta(forms.widgets.Textarea):
	attrs = {
		'cols': 60,
		'rows': 1,
		'style': 'resize:none;'
		}

class FormProposal(forms.ModelForm):

	dospem = forms.ModelChoiceField(queryset=Dosen.objects.all(), to_field_name="nidn")
	class Meta:
		model = Proposal
		fields = ['judul', 'katakunci', 'ringkasan', 'dospem', 'akun']
		widgets = {
				'judul': forms.Textarea(attrs={'cols': 60, 'rows': 1, 'style': 'resize:none;'}),
				'katakunci': forms.Textarea(attrs={'cols': 60, 'rows': 1, 'style': 'resize:none;'}),
				'ringkasan': forms.Textarea(attrs={'cols': 60, 'rows': 1, 'style': 'resize:none;'}),
				'dospem': forms.HiddenInput,
				'akun': forms.HiddenInput
			}


class FormBimbingan(forms.ModelForm):
	class Meta:
		model = BimbinganProposal
		fields = ['hasil', 'tanggal', 'proposal']
		widgets = {
			'hasil': forms.Textarea(attrs={'cols': 60, 'rows': 1, 'style': 'resize:none;'}),
			'tanggal': Tanggal()
		}


class FormSeminar(forms.ModelForm):
	class Meta:
		model = SeminarProposal
		fields = ['fileProposal', 'proposal']

proposal/views.py
# coding=utf-8
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from proposal.models import *
from proposal.forms import *
from django.views.generic import View
from django.views.generic.edit import UpdateView

# Create your views here.

app_name = 'proposal'

class Index(View):
	template_name = 'indexproposal.html'
	context = {}

	def get(self, request):
		form = FormProposal(None)
		self.context.update({
			'user': Mahasiswa.objects.get(akunMhs=request.user),
			'form': form
			})
		try:
			prop = Proposal.objects.get(akun=request.user)
			self.context.update({
				'prop': prop
				})
		except Proposal.DoesNotExist:
			pass
		finally:
			return render(request, self.template_name, self.context)

	def post(self, request):
		form = FormProposal(request.POST)
		if form.is_valid():
			o = form.save(commit=False)
			o.dospem = Dosen.objects.get(nidn=request.POST['dospem'])
			o.akun = request.user
			o.save()
		else:
			pass

		return redirect('proposal:index')



class Bimbingan(View):
	"""
	Kelas ini dibuat untuk memberikan hasil ke dalam Bimbingan
	"""
	template_name = "bimbinganproposal.html"
	form = FormBimbingan
	content = {}

	def get(self, request):
		"""
		untuk menampilkan hasil semua bimbingan
		:param request:
		:return:
		"""
		form = FormBimbingan(None)
		self.content.update(dict(form=form))
		try:
			proposal = Proposal.objects.get(akun=request.user)
			try:
				hasilbimbingan = BimbinganProposal.objects.filter(proposal=proposal)
				self.content.update(dict(hasil=hasilbimbingan))
			except BimbinganProposal.DoesNotExist:
				self.content.update(dict(error_Bimbingan="Anda belum bimbingan samsek"))
		except Proposal.DoesNotExist:
			self.content.update(dict(error_proposal="Anda belum membuat proposal"))
		finally:
			return render(request, self.template_name, self.content)

	def post(self, request):
		"""
		fungsi untuk menambah bimbingan ke dalam database
		:param request:
		:return:
		"""
		form = FormBimbingan(request.POST)
		if form.is_valid():
			a = form.save(commit=False)
			a.proposal = Proposal.objects.get(akun=request.user)
			a.save()
		else:
			self.content.update(dict(error_post="Form yang anda buat tidak valid, periksa kembali form anda"))

		return redirect('proposal:bimbingan')


class Seminar(View):
	"""
		Ini untuk seminar proposal, dari informasi sampe daftar
	"""

	template_name = "sidangproposal.html"
	content = {
		'ada': False
		}
	seminar = SeminarProposal

	def get(self, request):
		"""
			untuk menampilkan form pendaftaran
		:param request:
		:return:
		"""
		form = FormSeminar(None)
		self.content.update(dict(form=form))
		try:
			prop = Proposal.objects.get(akun=request.user)
			try:
				p = BimbinganProposal.objects.filter(proposal=prop).count()
				# print(p)
				if p > 3:
					masabimbingan = 'checked'
				else:
					masabimbingan = ' '
				self.content.update(dict(masabimbingan=masabimbingan))
			except BimbinganProposal.DoesNotExist:
				self.content.update(dict(error="anda belum melakukan bimbingan samsek"))
		except Proposal.DoesNotExist:
			self.content.update(dict(error="anda belum membuat proposal"))
		finally:
			return render(request, 'sidangproposal.html', self.content)

	def post(self, request):
		"""
		untuk daftar seminar gitu loh
		:param request:
		:return: hasil
		"""
		form = FormSeminar(request.POST, request.FILES)
		if form.is_valid():
			o = form.save(commit=False)
			o.proposal = Proposal.objects.get(akun=request.user)
			o.save()
			self.content.update({'ada': True})
			return redirect('proposal:seminar')
		else:
			self.content.update(dict(error_post="Form yang anda buat tidak valid, periksa kembali form anda"))
			return render(request, self.template_name, self.content)
		return redirect('proposal:index')


class Edit(UpdateView):
	model = Proposal
	fields = ['judul', 'katakunci', 'ringkasan', 'dospem']
	template_name = 'indexproposal.html'
	success_url = reverse_lazy('proposal:index')

proposal/templates/bimbinganproposal.html
{% extends 'base.html' %}

{% block title %} Bimbingan Proposal {% endblock %}

{% block content%}
{% if error_proposal is None %}
    <table class="mui-table">
<form class="mui-form--inline" method="post">
	{% csrf_token %}
	<td>
		<div class="mui-textfield mui-textfield--float-label required">
			<input type="number" id="no" required min="1" max="16">
			<label>Pertemuan ke</label>
		</div>
	</td>

	<td>
		<div class="mui-textfield">
			{{ form.tanggal }}
			<label>Tanggal</label>
		</div>
	</td>

	<td>
		<div class="mui-textfield mui-textfield--float-label">
			{{ form.hasil }}
			<label>Hasil Bimbingan</label>
		</div>
	</td>
	<td>
		<button type="submit" class="mui-btn mui-btn--raised "><span class="mdi-plus-circle-outline">+</span></button>
	</td>
</form>
</table>
    {% if error_Bimbingan is None %}
         <table class="mui-table mui-table--bordered">
            <thead>
                <th> Bimbingan ke </th>
                <th> Tanggal Bimbingan</th>
                <th> Hasil Bimbingan</th>
            </thead>

            {% for c in hasil%}
            <tr>
                <td> {{forloop.counter}} </td>
                <td> {{c.tanggal| date:"d M Y "}} </td>
                <td><a href=""> {{c.hasil | truncatechars:4}} </a></td>
            </tr>
            {% endfor %}
        </table>

    {% else %}
        <h1> {{ error_Bimbingan }} </h1>
    {% endif %}
{% else %}
    <h1 class="mui--text-danger">{{ error_proposal }} </h1>
{% endif %}


{% endblock %}

proposal/templates/indexproposal.html
{%extends "base.html"%}
{%block title%} Proposal {%endblock%}

{% block judul %} Proposal {%endblock%}

{%block content%}
{% if prop is None %}
    {% include 'proposal/proposal_form.html' %}
{% else %}
<div>
    <div class="mui-panel" style="padding-top: 50px; text-align: center;">
        <a href="{% url 'proposal:edit' prop.pk %}" class="mui--pull-right"> Edit </a>
        <h2> {{ prop.judul }} </h2>
        <i> Diajukan oleh: </i>
        <h3>
            {{ user.akunMhs.first_name }} {{ user.akunMhs.last_name }}
        </h3>
        <h4> NPM : {{ user.npm }} </h4>
        <i> Dosen Pembimbing : {{ prop.dospem }} {{ prop.dospem.gelar }}</i>
        <hr>
        <p> {{ prop.ringkasan }} </p>
        <hr>
        <i> <p>Kata Kunci : {{ prop.katakunci }}</p></i>
    </div>
</div>

{% endif %}

{%endblock%}

proposal/templates/sidangproposal.html
{% extends 'base.html' %}
{% block title %}
    Seminar Proposal
{% endblock %}
{%block judul%} Sidang Prpoposal {%endblock%}

{%block content%}
    {% if ada %}
        <div class="mui-panel">
      <h1> Anda Sudah Mendaftar Seminar</h1>
        <h2>  Silakan tunggu pemberitahuan untuk waktu dan tempat sidang </h2>
    </div>

    {% else %}
	<div class="mui-panel">
        <h1> Selamat, perjalanan anda hampir selesai, </h1>
        <h2> Untuk sidang, anda harus mengecek kembali kelengkapan sidang anda </h2>
        <h1>{{ oke }}</h1>
        <form class="mui-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mui-checkbox">
                <input type="checkbox" id="dospem" name="bimbingan" {{ masabimbingan }} disabled required>
                <label for="dospem"> Bimbingan lebih dari 3 (tiga) kali? </label>
            </div>

            <div class="mui-checkbox">
                <input type="checkbox" id="persetujuan" name="persetujuan" readonly {{ persetujuan }} required>
                <label for="persetujuan">  Dosen Pembimbing OK? </label>
            </div>

            <div class="mui-file">
                <label for="fileprop"> Upload file proposalnya di sini</label>
                {{ form.fileProposal }}
            </div>

            <button type="submit" class="mui-btn mui-btn--primary mui-btn--raised"> Bawa aku pergi dari sini ! </button>

        </form>
    </div>
    {% endif %}
{%endblock%}

proposal/templates/sidprop.html
{% extends 'base.html' %}

{%block judul%} Sidang Prpoposal {%endblock%}

{%block content%}
	<div class="mui-panel">
        <h1> Selamat, perjalanan anda hampir selesai, </h1>
        <h2> Untuk sidang, anda harus mengecek kembali kelengkapan sidang anda </h2>

        <form class="mui-form" method="post" >
            {% csrf_token %}
            <div class="mui-checkbox">
                <input type="checkbox" id="dospem" name="bimbingan" checked="{{a}}" disabled required>
                <label for="dospem"> Bimbingan lebih dari 3 (tiga) kali? </label>
            </div>

            <div class="mui-checkbox">
                <input type="checkbox" id="persetujuan" name="persetujuan" disabled required>
                <label for="persetujuan">  Dosen Pembimbing OK? </label>
            </div>

            <div class="mui-checkbox">
                <input type="checkbox" name="dospem" required>
                <label for="dospem"> Dosen Pembimbing </label>
            </div>

            <div class="mui-file">
                <label for="fileprop"> Upload file proposalnya di sini</label>
                <input type="file" required name="fileprop" id="fileprop" aria-modal="true">
            </div>

            <button type="submit" class="mui-btn mui-btn--primary mui-btn--raised"> Bawa aku pergi dari sini ! </button>

        </form>
    </div>
{%endblock%}